volumes:
  grafana_data:

services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3005:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      ENABLE_LOGS_LOKI: true

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  default:
    external: true
    name: scoobydoo
